import Head from 'next/head'
import {ComponentWithComplexState as FirstExample} from "../examples/example-01";
import {ComponentWithComplexState as SecondExample} from "../examples/example-02";
import {ComponentWithComplexState as ThirdExample} from "../examples/example-03";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <>
              <FirstExample userId="1" />
              <div style={{ height: 50 }} />
              <SecondExample />
              <div style={{ height: 50 }} />
              <ThirdExample />
          </>
      </main>
    </>
  )
}
